config/routes.rb
Rails.application.routes.draw do

  match '/scan_code' => 'code_scan#scan_code_get', via: :get 
  match '/scan_code' => 'code_scan#scan_code_post', via: :post

  root 'static_pages#dashboard'
  get '/create_account' => 'users#new'

  get 'logout'  => 'sessions#destroy'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/dashboard' => 'static_pages#dashboard'
  get '/all_scans' => 'units#all'
  get '/search' => 'units#search'
  get '/flagged' => 'units#flagged'
  get '/flag/unit/:id' => 'units#flag'
  get '/unflag/unit/:id' => 'units#unflag'
  match '/ajaxflag/:id' => 'units#ajax_flagger', via: :post

  resources :companies
  resources :units
  resources :users

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :company

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |unit|
        csv << unit.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy, :ajax_flagger]


  # GET /units
  # GET /units.json
  def index

    @units = []
    uniq_units = Unit.uniq.pluck(:unit_number)

    uniq_units.each do |base|
    units = Unit.where(unit_number: base)
    @units << units.order(:created_at).last

    end
  end

  def all
    @units = Unit.order(:created_at).reverse
    
    @xlsUnits = Unit.all
    respond_to do |format|
      format.html
      format.xml { render :xml => @xlsUnits}
      format.xls { send_data @xlsUnits.to_xls, :filename => 'units.xls' }
    end
  end

  def search
    number = params[:search]
    @units = []
    if number != nil
      Unit.all.each do |unit|
      time = Time.parse(unit.updated_at.to_s).in_time_zone("Central Time (US & Canada)")
        if unit.unit_number[number.upcase]
          @units << unit 
        end
      end
    end

  end

  def ajax_flagger
    if @unit.flagged == true
      @unit.update(flagged: false)
    else
      @unit.update(flagged: true)
    end
    redirect_to @unit
  end

  def flagged 
    @units = Unit.where(flagged: true)
    respond_to do |format|
      format.html
      format.xml { render :xml => @units }
      format.xls { send_data @units.to_xls, :filename => 'flagged_units.xls' }
    end
  end



  # GET /units/1
  # GET /units/1.json
  def show
    
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json

  def create
    respond_to do |format|
      if @unit.save
        @unit.update(address: parse_address(@unit.address))
        parse_coordinates(@unit)
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params[:unit].permit(:unit_number, :longitude, :latitude, :address, :username)
    end



end

app/helpers/units_helper.rb
module UnitsHelper

  def parse_address(unit)
    unit = Unit.find(unit.id)
    if 
      address = unit.street.to_s + " " + unit.zip.to_s + " " + unit.city.to_s + " " + unit.state.to_s
      address
    else
      address = "address format cannot be read"
      address
    end
  end

  def is_flagged(unit)
    unit.flagged
  end
end


# "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")

app/views/units/all.html.erb
<% if current_user %>
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                All Scans
                <small>Scanned Units</small>
            </h2>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="/dashboard">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-file" style="color:green"></i> All Scans
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->

<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-barcode fa-fw" style="color:green"></i> All Scans</h3>
            
        </div>
        <br>
        <%= render "layouts/search_bar" %>
            <div class="text-right">
                <a href="/all_scans.xls" class="btn btn-info wow bounceIn" data-wow-delay=".2s">Download Excell<i class="fa fa-arrow-circle-right"></i></a>
                <a href="/all_scans.csv" class="btn btn-default wow bounceIn" data-wow-delay=".4s">Download CSV<i class="fa fa-arrow-circle-right"></i></a>
            </div>
        <div class="panel-body">
            <div class="table-responsive">
               <table id="table-pagination" data-url="data2.json" data-height="400" data-pagination="true" data-search="true" class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Unit Number</th>
                            <th>Created At</th>
                            <th>User</th>
                            <th>Address</th>
                            <th> Flagged?</th>
                        </tr>
                    </thead>
                    <% @units.each do |unit| %>
                    <% time = Time.parse(unit.created_at.to_s).in_time_zone("Central Time (US & Canada)") %>
                      <tr>
                        <td><strong> <%= link_to unit.unit_number, unit %></strong></td>
                        <td><%= link_to time.strftime("%m/%d/%Y at %I:%M%p CT"), unit%></td>
                        <td> <%= link_to unit.username, unit %></td>
                         <td> <%= link_to self.parse_address(unit), unit %></td>
                        <td><% if self.is_flagged(unit) %>
                            <i class="fa fa-flag wow tada" style="color:red"> Yes</i>
                            <% else %>
                            <i class="fa fa-circle" style="color:green"> No</i>
                            <% end %>
                        </td>

                      </tr>
                    <% end %>
                    <tbody>
  
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/units/all.xls.erb
<table id="table-pagination" data-url="data2.json" data-height="400" data-pagination="true" data-search="true" class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>Unit Number</th>
            <th>Last Updated</th>
            <th>User</th>
            <th>Address</th>
            <th> Flagged?</th>
        </tr>
    </thead>
    <% @units.each do |unit| %>
    <% time = Time.parse(unit.updated_at.to_s).in_time_zone("Central Time (US & Canada)") %>
      <tr>
        <td><strong> <%= link_to unit.unit_number, unit %></strong></td>
        <td><%= link_to time.strftime("%m/%d/%Y at %I:%M%p CT"), unit%></td>
        <td> <%= link_to unit.username, unit %></td>
         <td> <%= link_to unit.address, unit %></td>
        <td><% if self.is_flagged(unit) %>
            <i class="fa fa-flag" style="color:red"> Yes</i>
            <% else %>
            <i class="fa fa-circle" style="color:green"> No</i>
            <% end %>
        </td>

      </tr>
    <% end %>
    <tbody>

    </tbody>
</table>

app/views/units/edit.html.erb
the page you are looking for does not exist 
<br>
<%= link_to 'Back', units_path %>

app/views/units/flagged.html.erb
<% if current_user %>
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                Flagged Scans
                <small>Scanned Units</small>
            </h2>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="/dashboard">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-flag" style="color:orange"></i> Flagged Scans
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->

<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-flag fa-fw" style="color:orange"></i> Flagged Scans</h3>
            
        </div>
        <br>
        <%= render "layouts/search_bar" %>
            <div class="text-right">
                <a href="/flagged.xls" class="btn btn-info wow bounceIn" data-wow-delay=".2s">Download Excell<i class="fa fa-arrow-circle-right"></i></a>
                <a href="/flagged.csv" class="btn btn-default wow bounceIn" data-wow-delay=".4s">Download CSV<i class="fa fa-arrow-circle-right"></i></a>
            </div>
        <div class="panel-body">
            <div class="table-responsive">
               <table id="table-pagination" data-url="data2.json" data-height="400" data-pagination="true" data-search="true" class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Unit Number</th>
                            <th>Last Updated</th>
                            <th>User</th>
                            <th>Address</th>
                            <th> Flagged?</th>
                        </tr>
                    </thead>
                    <% @units.sort_by{|e| e[:created_at]}.reverse.each do |unit| %>
                    <% time = Time.parse(unit.updated_at.to_s).in_time_zone("Central Time (US & Canada)") %>
                      <tr>
                        <td><strong> <%= link_to unit.unit_number, unit %></strong></td>
                        <td><%= link_to time.strftime("%m/%d/%Y at %I:%M%p CT"), unit%></td>
                        <td> <%= link_to unit.username, unit %></td>
                        <td> <%= link_to self.parse_address(unit), unit %></td>
                        <td><% if self.is_flagged(unit) %>
                            <i class="fa fa-flag" style="color:red"> Yes</i>
                            <% else %>
                            <i class="fa fa-circle" style="color:green"> No</i>
                            <% end %>
                        </td>

                      </tr>
                    <% end %>
                    <tbody>
  
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/units/index.html.erb
<% if current_user %>
<p id="notice"><%= notice %></p>


<div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Listing Units
                <small>Individual Units</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="/dashboard">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> Individual Units
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->

<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-file fa-fw"></i> Listing Individual Units</h3>
        </div>
        <br>
        <%= render "layouts/search_bar" %>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Unit Number</th>
                            <th>Created At</th>
                            <th>Last User</th>
                            <th>Last Address</th>
                            <th>Scans</th>
                        </tr>
                    </thead>
                    <% @units.sort_by{|e| e[:created_at]}.reverse.each do |unit| %>
                    <% time = Time.parse(unit.created_at.to_s).in_time_zone("Central Time (US & Canada)") %>
                      <tr>
                        <td><strong> <%= link_to unit.unit_number, unit %></strong></td>
                        <td><%= link_to time.strftime("%m/%d/%Y at %I:%M%p CT"), unit%></td>
                        <td> <%= link_to unit.username, unit %></td>
                         <td> <%= link_to self.parse_address(unit), unit %></td>
                        <td><%= Unit.where(unit_number: unit.unit_number).count %></td>

                      </tr>
                    <% end %>
                    <tbody>
  
                    </tbody>
                </table>
            </div>
            <div class="text-right">
                <a href="/all_scans">View All Unit Scans <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/units/new.html.erb
the page you are looking for does not exist 
<br>
<%= link_to 'Back', units_path %>

app/views/units/search.html.erb
<% if current_user %>
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                All Scans
                <small>Scanned Units</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="/dashboard">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> All Scans
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->

<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> All Scans (ordered by most recent scan)</h3>
        </div>
        <%= render "layouts/search_bar" %>
        <div class="panel-body">
            <div class="table-responsive">
               <table id="table-pagination" data-url="data2.json" data-height="400" data-pagination="true" data-search="true" class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Unit Number</th>
                            <th>Last Updated</th>
                            <th>User</th>
                            <th>Address</th>
                            <th> Flagged?</th>
                        </tr>
                    </thead>
                    <%  @units.sort_by{|e| e[:created_at]}.reverse.each do |unit| %>
                    <% time = Time.parse(unit.created_at.to_s).in_time_zone("Central Time (US & Canada)") %>
                      <tr>
                        <td><strong> <%= link_to unit.unit_number, unit %></strong></td>
                        <td><%= link_to time.strftime("%m/%d/%Y at %I:%M%p CT"), unit%></td>
                        <td> <%= link_to unit.username, unit %></td>
                        <td> <%= link_to self.parse_address(unit), unit %></td>
                        <td><% if self.is_flagged(unit) %>
                            <i class="fa fa-flag" style="color:red"> Yes</i>
                            <% else %>
                            <i class="fa fa-circle" style="color:green"> No</i>
                            <% end %>
                        </td>

                      </tr>
                    <% end %>
                    <tbody>
  
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/units/show.html.erb
<% if current_user %>



<div style='width: 800px;'>
  <div id="one_marker" style='width: 800px; height: 400px;'></div>
</div>


<div class="panel-body">
  <div class="table-responsive">
      <table class="table table-bordered table-hover table-striped">
          <thead>
              <tr>
                  <th>Unit Number</th>
                  <th>Scanned at</th>
                  <th>User</th>
                  <th>Address</th>
                  <th>Scans</th>
              </tr>
          </thead>
          <% time = Time.parse(@unit.created_at.to_s).in_time_zone("Central Time (US & Canada)") %>
            <tr>
              <td><strong> <%=  @unit.unit_number %></strong></td>
              <td><%=  time.strftime("%m/%d/%Y at %I:%M%p CT")%></td>
              <td> <%=  @unit.username %></td>
               <td> <%= self.parse_address(@unit) %> </td>
              <td><%= Unit.where(unit_number: @unit.unit_number).count %></td>

            </tr>
          <tbody>

          </tbody>
      </table>
  </div>

  <div align="center"> 
    <!-- Ajax with remote true, need show.js page to update which button to display -->
    <% if @unit.flagged == false %>
        <%= link_to 'Flag Me', '/ajaxflag/'+ @unit.id.to_s , method: :post, class: "btn btn-warning btn-lg" %>
    <% else %>
        <%= link_to 'Un-Flag Me', '/ajaxflag/'+ @unit.id.to_s , method: :post, class: "btn btn-success btn-lg" %>
    <% end %>
  </div>
</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'one_marker'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": '<%= j @unit.longitude %>',
        "lng": '<%= j @unit.latitude %>',
        "picture": {
          
          "width":  36,
          "height": 36
        },
        "infowindow": "hello!"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(16)
  });
</script>

<% end %>