config/routes.rb
Rails.application.routes.draw do

  match '/scan_code' => 'code_scan#scan_code_get', via: :get 
  match '/scan_code' => 'code_scan#scan_code_post', via: :post

  root 'static_pages#dashboard'
  get '/create_account' => 'users#new'

  get 'logout'  => 'sessions#destroy'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/dashboard' => 'static_pages#dashboard'
  get '/all_scans' => 'units#all'
  get '/search' => 'units#search'
  get '/flagged' => 'units#flagged'
  get '/flag/unit/:id' => 'units#flag'
  get '/unflag/unit/:id' => 'units#unflag'
  match '/ajaxflag/:id' => 'units#ajax_flagger', via: :post

  resources :companies
  resources :units
  resources :users

end

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">IVTServer for DWMorgan</a>
    </div>


    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
            <ul class="dropdown-menu alert-dropdown">
                <% Unit.where(flagged: true).each do |flag| %>
                <li>
                    <a href="/units/<%=flag.id%>"><%= flag.unit_number%> <span class="label label-default" style="color:orange"> <i class="fa fa-fw fa-flag"></i></span></a>
                </li>
                <% end %>
                <li class="divider"></li>
                <li>
                    <a href="/flagged">View All Flagged</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <% if current_user != nil %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.username %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li class="divider"></li>
                <li>
                    <a href="/logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                </li>
            </ul>
            <% else %>
            <a href="/login"><i class="fa fa-user"></i> Login Here</a>
            <ul class="dropdown-menu">
                <li class="divider"></li>
                <li>
                    <a href="/login"><i class="fa fa-fw fa-power-on"></i> login</a>
                </li>
            </ul>
            <% end %>
        </li>
    </ul>



    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li>
                <a href="/dashboard"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="/units"><i class="fa fa-fw fa-truck" style="color:#337ab7"></i> Units</a>
            </li>
            <li>
                <a href="/all_scans"><i class="fa fa-fw fa-barcode" style="color:#5cb85c"></i> Scans</a>
            </li>
            <li>
                <a href="/flagged"><i class="fa fa-fw fa-flag" style="color:orange"></i> Flagged</a>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>

app/views/layouts/_search_bar.html.erb
<div class="search" align="center">
  <%= form_tag search_path, method: :get do %>
  <%= text_field_tag :search, params[:search], :placeholder => 'Search for Units', class: "search_bar" %>
  <%= submit_tag "Search", name: nil, class: "btn btn-search" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Server</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src="js/jquery.js"></script>
  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Unit tracker (DWMorgan)">
    <meta name="author" content="Keenan Sturtevant">

</head>
<body>
<div id="wrapper">
  <%= render '/layouts/navbar'%>  
    <div id="page-wrapper">
      <% if current_user == nil && @login_screen != true%>
      <div class="btn btn-warning btn-embossed">
        <a href="/login"><i class="fa fa-fw fa-power-off"></i> login</a>
      </div>
      <%end%>
      <%= yield %>
    </div>
</div>
</body>
</html>

<!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>